workflows:
  # Android Build
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 22
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  # iOS Build
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.4
      node: 22
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS (Simulator)
        script: |
          cd ios/App
          xcodebuild -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - ios/App/build/Build/Products/Debug-iphonesimulator/*.app
